export const countries = [
  {
    code: 'AD',
    code3: 'AND',
    img: 'https://www.worldometers.info/img/flags/small/tn_an-flag.gif',
    label: 'Andorra',
    numeric: '020',
    phone: '376',
  },
  {
    code: 'AE',
    code3: 'ARE',
    img: null,
    label: 'United Arab Emirates',
    numeric: '784',
    phone: '971',
  },
  {
    code: 'AF',
    code3: 'AFG',
    img: 'https://www.worldometers.info/img/flags/small/tn_af-flag.gif',
    label: 'Afghanistan',
    numeric: '004',
    phone: '93',
  },
  {
    code: 'AG',
    code3: 'ATG',
    img: 'https://www.worldometers.info/img/flags/small/tn_ac-flag.gif',
    label: 'Antigua and Barbuda',
    numeric: '028',
    phone: '1-268',
  },
  {
    code: 'AI',
    code3: 'AIA',
    img: null,
    label: 'Anguilla',
    numeric: '660',
    phone: '1-264',
  },
  {
    code: 'AL',
    code3: 'ALB',
    img: 'https://www.worldometers.info/img/flags/small/tn_al-flag.gif',
    label: 'Albania',
    numeric: '008',
    phone: '355',
  },
  {
    code: 'AM',
    code3: 'ARM',
    img: 'https://www.worldometers.info/img/flags/small/tn_am-flag.gif',
    label: 'Armenia',
    numeric: '051',
    phone: '374',
  },
  {
    code: 'AO',
    code3: 'AGO',
    img: 'https://www.worldometers.info/img/flags/small/tn_ao-flag.gif',
    label: 'Angola',
    numeric: '024',
    phone: '244',
  },
  {
    code: 'AQ',
    code3: 'ATA',
    img: null,
    label: 'Antarctica',
    numeric: '010',
    phone: '672',
  },
  {
    code: 'AR',
    code3: 'ARG',
    img: 'https://www.worldometers.info/img/flags/small/tn_ar-flag.gif',
    label: 'Argentina',
    numeric: '032',
    phone: '54',
  },
  {
    code: 'AS',
    code3: 'ASM',
    img: null,
    label: 'American Samoa',
    numeric: '016',
    phone: '1-684',
  },
  {
    code: 'AT',
    code3: 'AUT',
    img: 'https://www.worldometers.info/img/flags/small/tn_au-flag.gif',
    label: 'Austria',
    numeric: '040',
    phone: '43',
  },
  {
    code: 'AU',
    code3: 'AUS',
    img: 'https://www.worldometers.info/img/flags/small/tn_as-flag.gif',
    label: 'Australia',
    numeric: '036',
    phone: '61',
    suggested: true,
  },
  {
    code: 'AW',
    code3: 'ABW',
    img: null,
    label: 'Aruba',
    numeric: '533',
    phone: '297',
  },
  {
    code: 'AX',
    code3: 'ALA',
    img: null,
    label: 'Alland Islands',
    numeric: '248',
    phone: '358',
  },
  {
    code: 'AZ',
    code3: 'AZE',
    img: 'https://www.worldometers.info/img/flags/small/tn_aj-flag.gif',
    label: 'Azerbaijan',
    numeric: '031',
    phone: '994',
  },
  {
    code: 'BA',
    code3: 'BIH',
    img: 'https://www.worldometers.info/img/flags/small/tn_bk-flag.gif',
    label: 'Bosnia and Herzegovina',
    numeric: '070',
    phone: '387',
  },
  {
    code: 'BB',
    code3: 'BRB',
    img: 'https://www.worldometers.info/img/flags/small/tn_bb-flag.gif',
    label: 'Barbados',
    numeric: '052',
    phone: '1-246',
  },
  {
    code: 'BD',
    code3: 'BGD',
    img: 'https://www.worldometers.info/img/flags/small/tn_bg-flag.gif',
    label: 'Bangladesh',
    numeric: '050',
    phone: '880',
  },
  {
    code: 'BE',
    code3: 'BEL',
    img: 'https://www.worldometers.info/img/flags/small/tn_be-flag.gif',
    label: 'Belgium',
    numeric: '056',
    phone: '32',
  },
  {
    code: 'BF',
    code3: 'BFA',
    img: 'https://www.worldometers.info/img/flags/small/tn_uv-flag.gif',
    label: 'Burkina Faso',
    numeric: '854',
    phone: '226',
  },
  {
    code: 'BG',
    code3: 'BGR',
    img: 'https://www.worldometers.info/img/flags/small/tn_bu-flag.gif',
    label: 'Bulgaria',
    numeric: '100',
    phone: '359',
  },
  {
    code: 'BH',
    code3: 'BHR',
    img: 'https://www.worldometers.info/img/flags/small/tn_ba-flag.gif',
    label: 'Bahrain',
    numeric: '048',
    phone: '973',
  },
  {
    code: 'BI',
    code3: 'BDI',
    img: 'https://www.worldometers.info/img/flags/small/tn_by-flag.gif',
    label: 'Burundi',
    numeric: '108',
    phone: '257',
  },
  {
    code: 'BJ',
    code3: 'BEN',
    img: 'https://www.worldometers.info/img/flags/small/tn_bn-flag.gif',
    label: 'Benin',
    numeric: '204',
    phone: '229',
  },
  {
    code: 'BL',
    code3: 'BLM',
    img: null,
    label: 'Saint Barthelemy',
    numeric: '652',
    phone: '590',
  },
  {
    code: 'BM',
    code3: 'BMU',
    img: null,
    label: 'Bermuda',
    numeric: '060',
    phone: '1-441',
  },
  {
    code: 'BN',
    code3: 'BRN',
    img: null,
    label: 'Brunei Darussalam',
    numeric: '096',
    phone: '673',
  },
  {
    code: 'BO',
    code3: 'BOL',
    img: null,
    label: 'Bolivia',
    numeric: '068',
    phone: '591',
  },
  {
    code: 'BR',
    code3: 'BRA',
    img: 'https://www.worldometers.info/img/flags/small/tn_br-flag.gif',
    label: 'Brazil',
    numeric: '076',
    phone: '55',
  },
  {
    code: 'BS',
    code3: 'BHS',
    img: null,
    label: 'Bahamas',
    numeric: '044',
    phone: '1-242',
  },
  {
    code: 'BT',
    code3: 'BTN',
    img: 'https://www.worldometers.info/img/flags/small/tn_bt-flag.gif',
    label: 'Bhutan',
    numeric: '064',
    phone: '975',
  },
  {
    code: 'BV',
    code3: 'BVT',
    img: null,
    label: 'Bouvet Island',
    numeric: '074',
    phone: '47',
  },
  {
    code: 'BW',
    code3: 'BWA',
    img: 'https://www.worldometers.info/img/flags/small/tn_bc-flag.gif',
    label: 'Botswana',
    numeric: '072',
    phone: '267',
  },
  {
    code: 'BY',
    code3: 'BLR',
    img: 'https://www.worldometers.info/img/flags/small/tn_bo-flag.gif',
    label: 'Belarus',
    numeric: '112',
    phone: '375',
  },
  {
    code: 'BZ',
    code3: 'BLZ',
    img: 'https://www.worldometers.info/img/flags/small/tn_bh-flag.gif',
    label: 'Belize',
    numeric: '084',
    phone: '501',
  },
  {
    code: 'CA',
    code3: 'CAN',
    img: 'https://www.worldometers.info/img/flags/small/tn_ca-flag.gif',
    label: 'Canada',
    numeric: '124',
    phone: '1',
    suggested: true,
  },
  {
    code: 'CC',
    code3: 'CCK',
    img: null,
    label: 'Cocos (Keeling) Islands',
    numeric: '166',
    phone: '61',
  },
  {
    code: 'CD',
    code3: 'COD',
    img: null,
    label: 'Congo, Democratic Republic of the',
    numeric: '180',
    phone: '243',
  },
  {
    code: 'CF',
    code3: 'CAF',
    img: null,
    label: 'Central African Republic',
    numeric: '140',
    phone: '236',
  },
  {
    code: 'CG',
    code3: 'COG',
    img: null,
    label: 'Congo, Republic of the',
    numeric: '178',
    phone: '242',
  },
  {
    code: 'CH',
    code3: 'CHE',
    img: 'https://www.worldometers.info/img/flags/small/tn_sz-flag.gif',
    label: 'Switzerland',
    numeric: '756',
    phone: '41',
  },
  {
    code: 'CI',
    code3: 'CIV',
    img: 'https://www.worldometers.info/img/flags/small/tn_iv-flag.gif',
    label: "Cote d'Ivoire",
    numeric: '384',
    phone: '225',
  },
  {
    code: 'CK',
    code3: 'COK',
    img: null,
    label: 'Cook Islands',
    numeric: '184',
    phone: '682',
  },
  {
    code: 'CL',
    code3: 'CHL',
    img: 'https://www.worldometers.info/img/flags/small/tn_ci-flag.gif',
    label: 'Chile',
    numeric: '152',
    phone: '56',
  },
  {
    code: 'CM',
    code3: 'CMR',
    img: 'https://www.worldometers.info/img/flags/small/tn_cm-flag.gif',
    label: 'Cameroon',
    numeric: '120',
    phone: '237',
  },
  {
    code: 'CN',
    code3: 'CHN',
    img: 'https://www.worldometers.info/img/flags/small/tn_ch-flag.gif',
    label: 'China',
    numeric: '156',
    phone: '86',
  },
  {
    code: 'CO',
    code3: 'COL',
    img: 'https://www.worldometers.info/img/flags/small/tn_co-flag.gif',
    label: 'Colombia',
    numeric: '170',
    phone: '57',
  },
  {
    code: 'CR',
    code3: 'CRI',
    img: 'https://www.worldometers.info/img/flags/small/tn_cs-flag.gif',
    label: 'Costa Rica',
    numeric: '188',
    phone: '506',
  },
  {
    code: 'CU',
    code3: 'CUB',
    img: 'https://www.worldometers.info/img/flags/small/tn_cu-flag.gif',
    label: 'Cuba',
    numeric: '192',
    phone: '53',
  },
  {
    code: 'CV',
    code3: 'CPV',
    img: 'https://www.worldometers.info/img/flags/small/tn_cv-flag.gif',
    label: 'Cape Verde',
    numeric: '132',
    phone: '238',
  },
  {
    code: 'CW',
    code3: 'CUW',
    img: null,
    label: 'Curacao',
    numeric: '531',
    phone: '599',
  },
  {
    code: 'CX',
    code3: 'CXR',
    img: null,
    label: 'Christmas Island',
    numeric: '162',
    phone: '61',
  },
  {
    code: 'CY',
    code3: 'CYP',
    img: 'https://www.worldometers.info/img/flags/small/tn_cy-flag.gif',
    label: 'Cyprus',
    numeric: '196',
    phone: '357',
  },
  {
    code: 'CZ',
    code3: 'CZE',
    img: 'https://www.worldometers.info/img/flags/small/tn_ez-flag.gif',
    label: 'Czech Republic',
    numeric: '203',
    phone: '420',
  },
  {
    code: 'DE',
    code3: 'DEU',
    img: 'https://www.worldometers.info/img/flags/small/tn_gm-flag.gif',
    label: 'Germany',
    numeric: '276',
    phone: '49',
    suggested: true,
  },
  {
    code: 'DJ',
    code3: 'DJI',
    img: 'https://www.worldometers.info/img/flags/small/tn_dj-flag.gif',
    label: 'Djibouti',
    numeric: '262',
    phone: '253',
  },
  {
    code: 'DK',
    code3: 'DNK',
    img: 'https://www.worldometers.info/img/flags/small/tn_da-flag.gif',
    label: 'Denmark',
    numeric: '208',
    phone: '45',
  },
  {
    code: 'DM',
    code3: 'DMA',
    img: 'https://www.worldometers.info/img/flags/small/tn_do-flag.gif',
    label: 'Dominica',
    numeric: '212',
    phone: '1-767',
  },
  {
    code: 'DO',
    code3: 'DOM',
    img: null,
    label: 'Dominican Republic',
    numeric: '214',
    phone: '1-809',
  },
  {
    code: 'DZ',
    code3: 'DZA',
    img: 'https://www.worldometers.info/img/flags/small/tn_ag-flag.gif',
    label: 'Algeria',
    numeric: '012',
    phone: '213',
  },
  {
    code: 'EC',
    code3: 'ECU',
    img: 'https://www.worldometers.info/img/flags/small/tn_ec-flag.gif',
    label: 'Ecuador',
    numeric: '218',
    phone: '593',
  },
  {
    code: 'EE',
    code3: 'EST',
    img: 'https://www.worldometers.info/img/flags/small/tn_en-flag.gif',
    label: 'Estonia',
    numeric: '233',
    phone: '372',
  },
  {
    code: 'EG',
    code3: 'EGY',
    img: 'https://www.worldometers.info/img/flags/small/tn_eg-flag.gif',
    label: 'Egypt',
    numeric: '818',
    phone: '20',
  },
  {
    code: 'EH',
    code3: 'ESH',
    img: null,
    label: 'Western Sahara',
    numeric: '732',
    phone: '212',
  },
  {
    code: 'ER',
    code3: 'ERI',
    img: 'https://www.worldometers.info/img/flags/small/tn_er-flag.gif',
    label: 'Eritrea',
    numeric: '232',
    phone: '291',
  },
  {
    code: 'ES',
    code3: 'ESP',
    img: 'https://www.worldometers.info/img/flags/small/tn_sp-flag.gif',
    label: 'Spain',
    numeric: '724',
    phone: '34',
  },
  {
    code: 'ET',
    code3: 'ETH',
    img: 'https://www.worldometers.info/img/flags/small/tn_et-flag.gif',
    label: 'Ethiopia',
    numeric: '231',
    phone: '251',
  },
  {
    code: 'FI',
    code3: 'FIN',
    img: 'https://www.worldometers.info/img/flags/small/tn_fi-flag.gif',
    label: 'Finland',
    numeric: '246',
    phone: '358',
  },
  {
    code: 'FJ',
    code3: 'FJI',
    img: 'https://www.worldometers.info/img/flags/small/tn_fj-flag.gif',
    label: 'Fiji',
    numeric: '242',
    phone: '679',
  },
  {
    code: 'FK',
    code3: 'FLK',
    img: null,
    label: 'Falkland Islands (Malvinas)',
    numeric: '238',
    phone: '500',
  },
  {
    code: 'FM',
    code3: 'FSM',
    img: null,
    label: 'Micronesia, Federated States of',
    numeric: '583',
    phone: '691',
  },
  {
    code: 'FO',
    code3: 'FRO',
    img: null,
    label: 'Faroe Islands',
    numeric: '234',
    phone: '298',
  },
  {
    code: 'FR',
    code3: 'FRA',
    img: 'https://www.worldometers.info/img/flags/small/tn_fr-flag.gif',
    label: 'France',
    numeric: '250',
    phone: '33',
    suggested: true,
  },
  {
    code: 'GA',
    code3: 'GAB',
    img: 'https://www.worldometers.info/img/flags/small/tn_gb-flag.gif',
    label: 'Gabon',
    numeric: '266',
    phone: '241',
  },
  {
    code: 'EN',
    code3: 'ENG',
    img: 'https://www.worldometers.info/img/flags/small/tn_uk-flag.gif',
    label: 'United Kingdom',
    numeric: '826',
    phone: '44',
  },
  {
    code: 'GD',
    code3: 'GRD',
    img: 'https://www.worldometers.info/img/flags/small/tn_gj-flag.gif',
    label: 'Grenada',
    numeric: '308',
    phone: '1-473',
  },
  {
    code: 'GE',
    code3: 'GEO',
    img: 'https://www.worldometers.info/img/flags/small/tn_gg-flag.gif',
    label: 'Georgia',
    numeric: '268',
    phone: '995',
  },
  {
    code: 'GF',
    code3: 'GUF',
    img: null,
    label: 'French Guiana',
    numeric: '254',
    phone: '594',
  },
  {
    code: 'GG',
    code3: 'GGY',
    img: null,
    label: 'Guernsey',
    numeric: '831',
    phone: '44',
  },
  {
    code: 'GH',
    code3: 'GHA',
    img: 'https://www.worldometers.info/img/flags/small/tn_gh-flag.gif',
    label: 'Ghana',
    numeric: '288',
    phone: '233',
  },
  {
    code: 'GI',
    code3: 'GIB',
    img: null,
    label: 'Gibraltar',
    numeric: '292',
    phone: '350',
  },
  {
    code: 'GL',
    code3: 'GRL',
    img: null,
    label: 'Greenland',
    numeric: '304',
    phone: '299',
  },
  {
    code: 'GM',
    code3: 'GMB',
    img: null,
    label: 'Gambia',
    numeric: '270',
    phone: '220',
  },
  {
    code: 'GN',
    code3: 'GIN',
    img: 'https://www.worldometers.info/img/flags/small/tn_gv-flag.gif',
    label: 'Guinea',
    numeric: '324',
    phone: '224',
  },
  {
    code: 'GP',
    code3: 'GLP',
    img: null,
    label: 'Guadeloupe',
    numeric: '312',
    phone: '590',
  },
  {
    code: 'GQ',
    code3: 'GNQ',
    img: 'https://www.worldometers.info/img/flags/small/tn_ek-flag.gif',
    label: 'Equatorial Guinea',
    numeric: '226',
    phone: '240',
  },
  {
    code: 'GR',
    code3: 'GRC',
    img: 'https://www.worldometers.info/img/flags/small/tn_gr-flag.gif',
    label: 'Greece',
    numeric: '300',
    phone: '30',
  },
  {
    code: 'GS',
    code3: 'SGS',
    img: null,
    label: 'South Georgia and the South Sandwich Islands',
    numeric: '239',
    phone: '500',
  },
  {
    code: 'GT',
    code3: 'GTM',
    img: 'https://www.worldometers.info/img/flags/small/tn_gt-flag.gif',
    label: 'Guatemala',
    numeric: '320',
    phone: '502',
  },
  {
    code: 'GU',
    code3: 'GUM',
    img: null,
    label: 'Guam',
    numeric: '316',
    phone: '1-671',
  },
  {
    code: 'GW',
    code3: 'GNB',
    img: 'https://www.worldometers.info/img/flags/small/tn_pu-flag.gif',
    label: 'Guinea-Bissau',
    numeric: '624',
    phone: '245',
  },
  {
    code: 'GY',
    code3: 'GUY',
    img: 'https://www.worldometers.info/img/flags/small/tn_gy-flag.gif',
    label: 'Guyana',
    numeric: '328',
    phone: '592',
  },
  {
    code: 'HK',
    code3: 'HKG',
    img: null,
    label: 'Hong Kong',
    numeric: '344',
    phone: '852',
  },
  {
    code: 'HM',
    code3: 'HMD',
    img: null,
    label: 'Heard Island and McDonald Islands',
    numeric: '334',
    phone: '672',
  },
  {
    code: 'HN',
    code3: 'HND',
    img: 'https://www.worldometers.info/img/flags/small/tn_ho-flag.gif',
    label: 'Honduras',
    numeric: '340',
    phone: '504',
  },
  {
    code: 'HR',
    code3: 'HRV',
    img: 'https://www.worldometers.info/img/flags/small/tn_hr-flag.gif',
    label: 'Croatia',
    numeric: '191',
    phone: '385',
  },
  {
    code: 'HT',
    code3: 'HTI',
    img: 'https://www.worldometers.info/img/flags/small/tn_ha-flag.gif',
    label: 'Haiti',
    numeric: '332',
    phone: '509',
  },
  {
    code: 'HU',
    code3: 'HUN',
    img: 'https://www.worldometers.info/img/flags/small/tn_hu-flag.gif',
    label: 'Hungary',
    numeric: '348',
    phone: '36',
  },
  {
    code: 'ID',
    code3: 'IDN',
    img: 'https://www.worldometers.info/img/flags/small/tn_id-flag.gif',
    label: 'Indonesia',
    numeric: '360',
    phone: '62',
  },
  {
    code: 'IE',
    code3: 'IRL',
    img: 'https://www.worldometers.info/img/flags/small/tn_ei-flag.gif',
    label: 'Ireland',
    numeric: '372',
    phone: '353',
  },
  {
    code: 'IL',
    code3: 'ISR',
    img: 'https://www.worldometers.info/img/flags/small/tn_is-flag.gif',
    label: 'Israel',
    numeric: '376',
    phone: '972',
  },
  {
    code: 'IM',
    code3: 'IMN',
    img: null,
    label: 'Isle of Man',
    numeric: '833',
    phone: '44',
  },
  {
    code: 'IN',
    code3: 'IND',
    img: 'https://www.worldometers.info/img/flags/small/tn_in-flag.gif',
    label: 'India',
    numeric: '356',
    phone: '91',
  },
  {
    code: 'IO',
    code3: 'IOT',
    img: null,
    label: 'British Indian Ocean Territory',
    numeric: '086',
    phone: '246',
  },
  {
    code: 'IQ',
    code3: 'IRQ',
    img: 'https://www.worldometers.info/img/flags/small/tn_iz-flag.gif',
    label: 'Iraq',
    numeric: '368',
    phone: '964',
  },
  {
    code: 'IR',
    code3: 'IRN',
    img: null,
    label: 'Iran, Islamic Republic of',
    numeric: '364',
    phone: '98',
  },
  {
    code: 'IS',
    code3: 'ISL',
    img: 'https://www.worldometers.info/img/flags/small/tn_ic-flag.gif',
    label: 'Iceland',
    numeric: '352',
    phone: '354',
  },
  {
    code: 'IT',
    code3: 'ITA',
    img: 'https://www.worldometers.info/img/flags/small/tn_it-flag.gif',
    label: 'Italy',
    numeric: '380',
    phone: '39',
  },
  {
    code: 'JE',
    code3: 'JEY',
    img: null,
    label: 'Jersey',
    numeric: '832',
    phone: '44',
  },
  {
    code: 'JM',
    code3: 'JAM',
    img: 'https://www.worldometers.info/img/flags/small/tn_jm-flag.gif',
    label: 'Jamaica',
    numeric: '388',
    phone: '1-876',
  },
  {
    code: 'JO',
    code3: 'JOR',
    img: 'https://www.worldometers.info/img/flags/small/tn_jo-flag.gif',
    label: 'Jordan',
    numeric: '400',
    phone: '962',
  },
  {
    code: 'JP',
    code3: 'JPN',
    img: 'https://www.worldometers.info/img/flags/small/tn_ja-flag.gif',
    label: 'Japan',
    numeric: '392',
    phone: '81',
    suggested: true,
  },
  {
    code: 'KE',
    code3: 'KEN',
    img: 'https://www.worldometers.info/img/flags/small/tn_ke-flag.gif',
    label: 'Kenya',
    numeric: '404',
    phone: '254',
  },
  {
    code: 'KG',
    code3: 'KGZ',
    img: 'https://www.worldometers.info/img/flags/small/tn_kg-flag.gif',
    label: 'Kyrgyzstan',
    numeric: '417',
    phone: '996',
  },
  {
    code: 'KH',
    code3: 'KHM',
    img: 'https://www.worldometers.info/img/flags/small/tn_cb-flag.gif',
    label: 'Cambodia',
    numeric: '116',
    phone: '855',
  },
  {
    code: 'KI',
    code3: 'KIR',
    img: 'https://www.worldometers.info/img/flags/small/tn_kr-flag.gif',
    label: 'Kiribati',
    numeric: '296',
    phone: '686',
  },
  {
    code: 'KM',
    code3: 'COM',
    img: null,
    label: 'Comoros',
    numeric: '174',
    phone: '269',
  },
  {
    code: 'KN',
    code3: 'KNA',
    img: 'https://www.worldometers.info/img/flags/small/tn_sc-flag.gif',
    label: 'Saint Kitts and Nevis',
    numeric: '659',
    phone: '1-869',
  },
  {
    code: 'KP',
    code3: 'PRK',
    img: null,
    label: "Korea, Democratic People's Republic of",
    numeric: '408',
    phone: '850',
  },
  {
    code: 'KR',
    code3: 'KOR',
    img: null,
    label: 'Korea, Republic of',
    numeric: '410',
    phone: '82',
  },
  {
    code: 'KW',
    code3: 'KWT',
    img: 'https://www.worldometers.info/img/flags/small/tn_ku-flag.gif',
    label: 'Kuwait',
    numeric: '414',
    phone: '965',
  },
  {
    code: 'KY',
    code3: 'CYM',
    img: null,
    label: 'Cayman Islands',
    numeric: '136',
    phone: '1-345',
  },
  {
    code: 'KZ',
    code3: 'KAZ',
    img: 'https://www.worldometers.info/img/flags/small/tn_kz-flag.gif',
    label: 'Kazakhstan',
    numeric: '398',
    phone: '7',
  },
  {
    code: 'LA',
    code3: 'LAO',
    img: null,
    label: "Lao People's Democratic Republic",
    numeric: '418',
    phone: '856',
  },
  {
    code: 'LB',
    code3: 'LBN',
    img: 'https://www.worldometers.info/img/flags/small/tn_le-flag.gif',
    label: 'Lebanon',
    numeric: '422',
    phone: '961',
  },
  {
    code: 'LC',
    code3: 'LCA',
    img: 'https://www.worldometers.info/img/flags/small/tn_st-flag.gif',
    label: 'Saint Lucia',
    numeric: '662',
    phone: '1-758',
  },
  {
    code: 'LI',
    code3: 'LIE',
    img: 'https://www.worldometers.info/img/flags/small/tn_ls-flag.gif',
    label: 'Liechtenstein',
    numeric: '438',
    phone: '423',
  },
  {
    code: 'LK',
    code3: 'LKA',
    img: 'https://www.worldometers.info/img/flags/small/tn_ce-flag.gif',
    label: 'Sri Lanka',
    numeric: '144',
    phone: '94',
  },
  {
    code: 'LR',
    code3: 'LBR',
    img: 'https://www.worldometers.info/img/flags/small/tn_li-flag.gif',
    label: 'Liberia',
    numeric: '430',
    phone: '231',
  },
  {
    code: 'LS',
    code3: 'LSO',
    img: 'https://www.worldometers.info/img/flags/small/tn_lt-flag.gif',
    label: 'Lesotho',
    numeric: '426',
    phone: '266',
  },
  {
    code: 'LT',
    code3: 'LTU',
    img: 'https://www.worldometers.info/img/flags/small/tn_lh-flag.gif',
    label: 'Lithuania',
    numeric: '440',
    phone: '370',
  },
  {
    code: 'LU',
    code3: 'LUX',
    img: 'https://www.worldometers.info/img/flags/small/tn_lu-flag.gif',
    label: 'Luxembourg',
    numeric: '442',
    phone: '352',
  },
  {
    code: 'LV',
    code3: 'LVA',
    img: 'https://www.worldometers.info/img/flags/small/tn_lg-flag.gif',
    label: 'Latvia',
    numeric: '428',
    phone: '371',
  },
  {
    code: 'LY',
    code3: 'LBY',
    img: 'https://www.worldometers.info/img/flags/small/tn_ly-flag.gif',
    label: 'Libya',
    numeric: '434',
    phone: '218',
  },
  {
    code: 'MA',
    code3: 'MAR',
    img: 'https://www.worldometers.info/img/flags/small/tn_mo-flag.gif',
    label: 'Morocco',
    numeric: '504',
    phone: '212',
  },
  {
    code: 'MC',
    code3: 'MCO',
    img: 'https://www.worldometers.info/img/flags/small/tn_mn-flag.gif',
    label: 'Monaco',
    numeric: '492',
    phone: '377',
  },
  {
    code: 'MD',
    code3: 'MDA',
    img: null,
    label: 'Moldova, Republic of',
    numeric: '498',
    phone: '373',
  },
  {
    code: 'ME',
    code3: 'MNE',
    img: 'https://www.worldometers.info/img/flags/small/tn_mj-flag.gif',
    label: 'Montenegro',
    numeric: '499',
    phone: '382',
  },
  {
    code: 'MF',
    code3: 'MAF',
    img: null,
    label: 'Saint Martin (French part)',
    numeric: '663',
    phone: '590',
  },
  {
    code: 'MG',
    code3: 'MDG',
    img: 'https://www.worldometers.info/img/flags/small/tn_ma-flag.gif',
    label: 'Madagascar',
    numeric: '450',
    phone: '261',
  },
  {
    code: 'MH',
    code3: 'MHL',
    img: null,
    label: 'Marshall Islands',
    numeric: '584',
    phone: '692',
  },
  {
    code: 'MK',
    code3: 'MKD',
    img: null,
    label: 'Macedonia, the Former Yugoslav Republic of',
    numeric: '807',
    phone: '389',
  },
  {
    code: 'ML',
    code3: 'MLI',
    img: 'https://www.worldometers.info/img/flags/small/tn_ml-flag.gif',
    label: 'Mali',
    numeric: '466',
    phone: '223',
  },
  {
    code: 'MM',
    code3: 'MMR',
    img: 'https://www.worldometers.info/img/flags/small/tn_bm-flag.gif',
    label: 'Myanmar',
    numeric: '104',
    phone: '95',
  },
  {
    code: 'MN',
    code3: 'MNG',
    img: 'https://www.worldometers.info/img/flags/small/tn_mg-flag.gif',
    label: 'Mongolia',
    numeric: '496',
    phone: '976',
  },
  {
    code: 'MO',
    code3: 'MAC',
    img: null,
    label: 'Macao',
    numeric: '446',
    phone: '853',
  },
  {
    code: 'MP',
    code3: 'MNP',
    img: null,
    label: 'Northern Mariana Islands',
    numeric: '580',
    phone: '1-670',
  },
  {
    code: 'MQ',
    code3: 'MTQ',
    img: null,
    label: 'Martinique',
    numeric: '474',
    phone: '596',
  },
  {
    code: 'MR',
    code3: 'MRT',
    img: 'https://www.worldometers.info/img/flags/small/tn_mr-flag.gif',
    label: 'Mauritania',
    numeric: '478',
    phone: '222',
  },
  {
    code: 'MS',
    code3: 'MSR',
    img: null,
    label: 'Montserrat',
    numeric: '500',
    phone: '1-664',
  },
  {
    code: 'MT',
    code3: 'MLT',
    img: 'https://www.worldometers.info/img/flags/small/tn_mt-flag.gif',
    label: 'Malta',
    numeric: '470',
    phone: '356',
  },
  {
    code: 'MU',
    code3: 'MUS',
    img: 'https://www.worldometers.info/img/flags/small/tn_mp-flag.gif',
    label: 'Mauritius',
    numeric: '480',
    phone: '230',
  },
  {
    code: 'MV',
    code3: 'MDV',
    img: 'https://www.worldometers.info/img/flags/small/tn_mv-flag.gif',
    label: 'Maldives',
    numeric: '462',
    phone: '960',
  },
  {
    code: 'MW',
    code3: 'MWI',
    img: 'https://www.worldometers.info/img/flags/small/tn_mi-flag.gif',
    label: 'Malawi',
    numeric: '454',
    phone: '265',
  },
  {
    code: 'MX',
    code3: 'MEX',
    img: 'https://www.worldometers.info/img/flags/small/tn_mx-flag.gif',
    label: 'Mexico',
    numeric: '484',
    phone: '52',
  },
  {
    code: 'MY',
    code3: 'MYS',
    img: 'https://www.worldometers.info/img/flags/small/tn_my-flag.gif',
    label: 'Malaysia',
    numeric: '458',
    phone: '60',
  },
  {
    code: 'MZ',
    code3: 'MOZ',
    img: 'https://www.worldometers.info/img/flags/small/tn_mz-flag.gif',
    label: 'Mozambique',
    numeric: '508',
    phone: '258',
  },
  {
    code: 'NA',
    code3: 'NAM',
    img: 'https://www.worldometers.info/img/flags/small/tn_wa-flag.gif',
    label: 'Namibia',
    numeric: '516',
    phone: '264',
  },
  {
    code: 'NC',
    code3: 'NCL',
    img: null,
    label: 'New Caledonia',
    numeric: '540',
    phone: '687',
  },
  {
    code: 'NE',
    code3: 'NER',
    img: null,
    label: 'Niger',
    numeric: '562',
    phone: '227',
  },
  {
    code: 'NF',
    code3: 'NFK',
    img: null,
    label: 'Norfolk Island',
    numeric: '574',
    phone: '672',
  },
  {
    code: 'NG',
    code3: 'NGA',
    img: 'https://www.worldometers.info/img/flags/small/tn_ni-flag.gif',
    label: 'Nigeria',
    numeric: '566',
    phone: '234',
  },
  {
    code: 'NI',
    code3: 'NIC',
    img: 'https://www.worldometers.info/img/flags/small/tn_nu-flag.gif',
    label: 'Nicaragua',
    numeric: '558',
    phone: '505',
  },
  {
    code: 'NL',
    code3: 'NLD',
    img: null,
    label: 'Netherlands',
    numeric: '528',
    phone: '31',
  },
  {
    code: 'NO',
    code3: 'NOR',
    img: 'https://www.worldometers.info/img/flags/small/tn_no-flag.gif',
    label: 'Norway',
    numeric: '578',
    phone: '47',
  },
  {
    code: 'NP',
    code3: 'NPL',
    img: 'https://www.worldometers.info/img/flags/small/tn_np-flag.gif',
    label: 'Nepal',
    numeric: '524',
    phone: '977',
  },
  {
    code: 'NR',
    code3: 'NRU',
    img: 'https://www.worldometers.info/img/flags/small/tn_nr-flag.gif',
    label: 'Nauru',
    numeric: '520',
    phone: '674',
  },
  {
    code: 'NU',
    code3: 'NIU',
    img: null,
    label: 'Niue',
    numeric: '570',
    phone: '683',
  },
  {
    code: 'NZ',
    code3: 'NZL',
    img: 'https://www.worldometers.info/img/flags/small/tn_nz-flag.gif',
    label: 'New Zealand',
    numeric: '554',
    phone: '64',
  },
  {
    code: 'OM',
    code3: 'OMN',
    img: 'https://www.worldometers.info/img/flags/small/tn_mu-flag.gif',
    label: 'Oman',
    numeric: '512',
    phone: '968',
  },
  {
    code: 'PA',
    code3: 'PAN',
    img: 'https://www.worldometers.info/img/flags/small/tn_pm-flag.gif',
    label: 'Panama',
    numeric: '591',
    phone: '507',
  },
  {
    code: 'PE',
    code3: 'PER',
    img: 'https://www.worldometers.info/img/flags/small/tn_pe-flag.gif',
    label: 'Peru',
    numeric: '604',
    phone: '51',
  },
  {
    code: 'PF',
    code3: 'PYF',
    img: null,
    label: 'French Polynesia',
    numeric: '258',
    phone: '689',
  },
  {
    code: 'PG',
    code3: 'PNG',
    img: 'https://www.worldometers.info/img/flags/small/tn_pp-flag.gif',
    label: 'Papua New Guinea',
    numeric: '598',
    phone: '675',
  },
  {
    code: 'PH',
    code3: 'PHL',
    img: null,
    label: 'Philippines',
    numeric: '608',
    phone: '63',
  },
  {
    code: 'PK',
    code3: 'PAK',
    img: 'https://www.worldometers.info/img/flags/small/tn_pk-flag.gif',
    label: 'Pakistan',
    numeric: '586',
    phone: '92',
  },
  {
    code: 'PL',
    code3: 'POL',
    img: 'https://www.worldometers.info/img/flags/small/tn_pl-flag.gif',
    label: 'Poland',
    numeric: '616',
    phone: '48',
  },
  {
    code: 'PM',
    code3: 'SPM',
    img: null,
    label: 'Saint Pierre and Miquelon',
    numeric: '666',
    phone: '508',
  },
  {
    code: 'PN',
    code3: 'PCN',
    img: null,
    label: 'Pitcairn',
    numeric: '612',
    phone: '870',
  },
  {
    code: 'PR',
    code3: 'PRI',
    img: null,
    label: 'Puerto Rico',
    numeric: '630',
    phone: '1',
  },
  {
    code: 'PS',
    code3: 'PSE',
    img: null,
    label: 'Palestine, State of',
    numeric: '275',
    phone: '970',
  },
  {
    code: 'PT',
    code3: 'PRT',
    img: 'https://www.worldometers.info/img/flags/small/tn_po-flag.gif',
    label: 'Portugal',
    numeric: '620',
    phone: '351',
  },
  {
    code: 'PW',
    code3: 'PLW',
    img: 'https://www.worldometers.info/img/flags/small/tn_ps-flag.gif',
    label: 'Palau',
    numeric: '585',
    phone: '680',
  },
  {
    code: 'PY',
    code3: 'PRY',
    img: 'https://www.worldometers.info/img/flags/small/tn_pa-flag.gif',
    label: 'Paraguay',
    numeric: '600',
    phone: '595',
  },
  {
    code: 'QA',
    code3: 'QAT',
    img: 'https://www.worldometers.info/img/flags/small/tn_qa-flag.gif',
    label: 'Qatar',
    numeric: '634',
    phone: '974',
  },
  {
    code: 'RE',
    code3: 'REU',
    img: null,
    label: 'Reunion',
    numeric: '638',
    phone: '262',
  },
  {
    code: 'RO',
    code3: 'ROU',
    img: 'https://www.worldometers.info/img/flags/small/tn_ro-flag.gif',
    label: 'Romania',
    numeric: '642',
    phone: '40',
  },
  {
    code: 'RS',
    code3: 'SRB',
    img: 'https://www.worldometers.info/img/flags/small/tn_ri-flag.gif',
    label: 'Serbia',
    numeric: '688',
    phone: '381',
  },
  {
    code: 'RU',
    code3: 'RUS',
    img: null,
    label: 'Russian Federation',
    numeric: '643',
    phone: '7',
  },
  {
    code: 'RW',
    code3: 'RWA',
    img: 'https://www.worldometers.info/img/flags/small/tn_rw-flag.gif',
    label: 'Rwanda',
    numeric: '646',
    phone: '250',
  },
  {
    code: 'SA',
    code3: 'SAU',
    img: 'https://www.worldometers.info/img/flags/small/tn_sa-flag.gif',
    label: 'Saudi Arabia',
    numeric: '682',
    phone: '966',
  },
  {
    code: 'SB',
    code3: 'SLB',
    img: 'https://www.worldometers.info/img/flags/small/tn_bp-flag.gif',
    label: 'Solomon Islands',
    numeric: '090',
    phone: '677',
  },
  {
    code: 'SC',
    code3: 'SYC',
    img: 'https://www.worldometers.info/img/flags/small/tn_se-flag.gif',
    label: 'Seychelles',
    numeric: '690',
    phone: '248',
  },
  {
    code: 'SD',
    code3: 'SDN',
    img: null,
    label: 'Sudan',
    numeric: '729',
    phone: '249',
  },
  {
    code: 'SE',
    code3: 'SWE',
    img: 'https://www.worldometers.info/img/flags/small/tn_sw-flag.gif',
    label: 'Sweden',
    numeric: '752',
    phone: '46',
  },
  {
    code: 'SG',
    code3: 'SGP',
    img: 'https://www.worldometers.info/img/flags/small/tn_sn-flag.gif',
    label: 'Singapore',
    numeric: '702',
    phone: '65',
  },
  {
    code: 'SH',
    code3: 'SHN',
    img: null,
    label: 'Saint Helena',
    numeric: '654',
    phone: '290',
  },
  {
    code: 'SI',
    code3: 'SVN',
    img: 'https://www.worldometers.info/img/flags/small/tn_si-flag.gif',
    label: 'Slovenia',
    numeric: '705',
    phone: '386',
  },
  {
    code: 'SJ',
    code3: 'SJM',
    img: null,
    label: 'Svalbard and Jan Mayen',
    numeric: '744',
    phone: '47',
  },
  {
    code: 'SK',
    code3: 'SVK',
    img: 'https://www.worldometers.info/img/flags/small/tn_lo-flag.gif',
    label: 'Slovakia',
    numeric: '703',
    phone: '421',
  },
  {
    code: 'SL',
    code3: 'SLE',
    img: 'https://www.worldometers.info/img/flags/small/tn_sl-flag.gif',
    label: 'Sierra Leone',
    numeric: '694',
    phone: '232',
  },
  {
    code: 'SM',
    code3: 'SMR',
    img: 'https://www.worldometers.info/img/flags/small/tn_sm-flag.gif',
    label: 'San Marino',
    numeric: '674',
    phone: '378',
  },
  {
    code: 'SN',
    code3: 'SEN',
    img: 'https://www.worldometers.info/img/flags/small/tn_sg-flag.gif',
    label: 'Senegal',
    numeric: '686',
    phone: '221',
  },
  {
    code: 'SO',
    code3: 'SOM',
    img: 'https://www.worldometers.info/img/flags/small/tn_so-flag.gif',
    label: 'Somalia',
    numeric: '706',
    phone: '252',
  },
  {
    code: 'SR',
    code3: 'SUR',
    img: 'https://www.worldometers.info/img/flags/small/tn_ns-flag.gif',
    label: 'Suriname',
    numeric: '740',
    phone: '597',
  },
  {
    code: 'SS',
    code3: 'SSD',
    img: 'https://www.worldometers.info/img/flags/small/tn_od-flag.gif',
    label: 'South Sudan',
    numeric: '728',
    phone: '211',
  },
  {
    code: 'ST',
    code3: 'STP',
    img: 'https://www.worldometers.info/img/flags/small/tn_tp-flag.gif',
    label: 'Sao Tome and Principe',
    numeric: '678',
    phone: '239',
  },
  {
    code: 'SV',
    code3: 'SLV',
    img: 'https://www.worldometers.info/img/flags/small/tn_es-flag.gif',
    label: 'El Salvador',
    numeric: '222',
    phone: '503',
  },
  {
    code: 'SX',
    code3: 'SXM',
    img: null,
    label: 'Sint Maarten (Dutch part)',
    numeric: '534',
    phone: '1-721',
  },
  {
    code: 'SY',
    code3: 'SYR',
    img: null,
    label: 'Syrian Arab Republic',
    numeric: '760',
    phone: '963',
  },
  {
    code: 'SZ',
    code3: 'SWZ',
    img: 'https://www.worldometers.info/img/flags/small/tn_wz-flag.gif',
    label: 'Swaziland',
    numeric: '748',
    phone: '268',
  },
  {
    code: 'TC',
    code3: 'TCA',
    img: null,
    label: 'Turks and Caicos Islands',
    numeric: '796',
    phone: '1-649',
  },
  {
    code: 'TD',
    code3: 'TCD',
    img: 'https://www.worldometers.info/img/flags/small/tn_cd-flag.gif',
    label: 'Chad',
    numeric: '148',
    phone: '235',
  },
  {
    code: 'TF',
    code3: 'ATF',
    img: null,
    label: 'French Southern Territories',
    numeric: '260',
    phone: '262',
  },
  {
    code: 'TG',
    code3: 'TGO',
    img: 'https://www.worldometers.info/img/flags/small/tn_to-flag.gif',
    label: 'Togo',
    numeric: '768',
    phone: '228',
  },
  {
    code: 'TH',
    code3: 'THA',
    img: 'https://www.worldometers.info/img/flags/small/tn_th-flag.gif',
    label: 'Thailand',
    numeric: '764',
    phone: '66',
  },
  {
    code: 'TJ',
    code3: 'TJK',
    img: 'https://www.worldometers.info/img/flags/small/tn_ti-flag.gif',
    label: 'Tajikistan',
    numeric: '762',
    phone: '992',
  },
  {
    code: 'TK',
    code3: 'TKL',
    img: null,
    label: 'Tokelau',
    numeric: '772',
    phone: '690',
  },
  {
    code: 'TL',
    code3: 'TLS',
    img: 'https://www.worldometers.info/img/flags/small/tn_tt-flag.gif',
    label: 'Timor-Leste',
    numeric: '626',
    phone: '670',
  },
  {
    code: 'TM',
    code3: 'TKM',
    img: 'https://www.worldometers.info/img/flags/small/tn_tx-flag.gif',
    label: 'Turkmenistan',
    numeric: '795',
    phone: '993',
  },
  {
    code: 'TN',
    code3: 'TUN',
    img: 'https://www.worldometers.info/img/flags/small/tn_ts-flag.gif',
    label: 'Tunisia',
    numeric: '788',
    phone: '216',
  },
  {
    code: 'TO',
    code3: 'TON',
    img: 'https://www.worldometers.info/img/flags/small/tn_tn-flag.gif',
    label: 'Tonga',
    numeric: '776',
    phone: '676',
  },
  {
    code: 'TR',
    code3: 'TUR',
    img: 'https://www.worldometers.info/img/flags/small/tn_tu-flag.gif',
    label: 'Turkey',
    numeric: '792',
    phone: '90',
  },
  {
    code: 'TT',
    code3: 'TTO',
    img: 'https://www.worldometers.info/img/flags/small/tn_td-flag.gif',
    label: 'Trinidad and Tobago',
    numeric: '780',
    phone: '1-868',
  },
  {
    code: 'TV',
    code3: 'TUV',
    img: 'https://www.worldometers.info/img/flags/small/tn_tv-flag.gif',
    label: 'Tuvalu',
    numeric: '798',
    phone: '688',
  },
  {
    code: 'TW',
    code3: 'TWN',
    img: null,
    label: 'Taiwan, Province of China',
    numeric: '158',
    phone: '886',
  },
  {
    code: 'TZ',
    code3: 'TZA',
    img: null,
    label: 'United Republic of Tanzania',
    numeric: '834',
    phone: '255',
  },
  {
    code: 'UA',
    code3: 'UKR',
    img: 'https://www.worldometers.info/img/flags/small/tn_up-flag.gif',
    label: 'Ukraine',
    numeric: '804',
    phone: '380',
  },
  {
    code: 'UG',
    code3: 'UGA',
    img: 'https://www.worldometers.info/img/flags/small/tn_ug-flag.gif',
    label: 'Uganda',
    numeric: '800',
    phone: '256',
  },
  {
    code: 'US',
    code3: 'USA',
    img: 'https://www.worldometers.info/img/flags/small/tn_us-flag.gif',
    label: 'United States',
    numeric: '840',
    phone: '1',
    suggested: true,
  },
  {
    code: 'UY',
    code3: 'URY',
    img: 'https://www.worldometers.info/img/flags/small/tn_uy-flag.gif',
    label: 'Uruguay',
    numeric: '858',
    phone: '598',
  },
  {
    code: 'UZ',
    code3: 'UZB',
    img: 'https://www.worldometers.info/img/flags/small/tn_uz-flag.gif',
    label: 'Uzbekistan',
    numeric: '860',
    phone: '998',
  },
  {
    code: 'VA',
    code3: 'VAT',
    img: null,
    label: 'Holy See (Vatican City State)',
    numeric: '336',
    phone: '379',
  },
  {
    code: 'VC',
    code3: 'VCT',
    img: null,
    label: 'Saint Vincent and the Grenadines',
    numeric: '670',
    phone: '1-784',
  },
  {
    code: 'VE',
    code3: 'VEN',
    img: null,
    label: 'Venezuela',
    numeric: '862',
    phone: '58',
  },
  {
    code: 'VG',
    code3: 'VGB',
    img: null,
    label: 'British Virgin Islands',
    numeric: '092',
    phone: '1-284',
  },
  {
    code: 'VI',
    code3: 'VIR',
    img: null,
    label: 'US Virgin Islands',
    numeric: '850',
    phone: '1-340',
  },
  {
    code: 'VN',
    code3: 'VNM',
    img: null,
    label: 'Vietnam',
    numeric: '704',
    phone: '84',
  },
  {
    code: 'VU',
    code3: 'VUT',
    img: 'https://www.worldometers.info/img/flags/small/tn_nh-flag.gif',
    label: 'Vanuatu',
    numeric: '548',
    phone: '678',
  },
  {
    code: 'WF',
    code3: 'WLF',
    img: null,
    label: 'Wallis and Futuna',
    numeric: '876',
    phone: '681',
  },
  {
    code: 'WS',
    code3: 'WSM',
    img: 'https://www.worldometers.info/img/flags/small/tn_ws-flag.gif',
    label: 'Samoa',
    numeric: '882',
    phone: '685',
  },
  {
    code: 'XK',
    code3: null,
    img: null,
    label: 'Kosovo',
    numeric: null,
    phone: '383',
  },
  {
    code: 'YE',
    code3: 'YEM',
    img: 'https://www.worldometers.info/img/flags/small/tn_ym-flag.gif',
    label: 'Yemen',
    numeric: '887',
    phone: '967',
  },
  {
    code: 'YT',
    code3: 'MYT',
    img: null,
    label: 'Mayotte',
    numeric: '175',
    phone: '262',
  },
  {
    code: 'ZA',
    code3: 'ZAF',
    img: 'https://www.worldometers.info/img/flags/small/tn_sf-flag.gif',
    label: 'South Africa',
    numeric: '710',
    phone: '27',
  },
  {
    code: 'ZM',
    code3: 'ZMB',
    img: 'https://www.worldometers.info/img/flags/small/tn_za-flag.gif',
    label: 'Zambia',
    numeric: '894',
    phone: '260',
  },
  {
    code: 'ZW',
    code3: 'ZWE',
    img: 'https://www.worldometers.info/img/flags/small/tn_zi-flag.gif',
    label: 'Zimbabwe',
    numeric: '716',
    phone: '263',
  },
]
